name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - "master"

env:
  REGISTRY: ghcr.io

jobs:
  build-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
    